defaults:
  - _self_
  - classifier: ???

projection: ???
classifier: ???
dataset: ???
dbm_resolution: 300

hydra:
  job:
    chdir: True
  mode: MULTIRUN
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}-${projection}-${classifier.name}-${dataset}
  sweeper:
    params:
      projection: tsne,umap,isomap
      classifier: nn
      dataset: mnist,fashionmnist,quickdraw
